# Generated by Django 6.0.3 on 2026-04-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('status', models.CharField(default='approved', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
