# Generated by Django 6.0.3 on 2026-04-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSubmission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=254)),
                ('requestType', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='userEmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
